require 'file_transfer_component/messages/events/not_found'
require 'file_transfer_component/messages/events/copied_to_s3'
require 'file_transfer_component/messages/events/initiated'
require 'file_transfer_component/messages/commands/initiate'
require 'file_transfer_component/commands/command'
require 'file_transfer_component/commands/initiate'
require 'file_transfer/client/namespace'
