source 'https://rubygems.org' do
  gem 'confstruct'
  gem 'hashie'
  gem 'io-console', "0.4.5"
  gem 'json'
  gem 'minitest'
  gem 'naught'
  gem 'net-telnet'
  gem 'pg'
  gem 'power_assert'
  gem 'psych'
  gem 'rainbow'
  gem 'rake'
  gem 'rdoc'
  gem 'test-unit'
  gem 'test_bench'
  gem 'thor'
  gem 'thread_safe'
  gem 'tzinfo'
  gem 'aws-sdk'
end

source 'https://gem.fury.io/eventide/' do
  gem 'async_invocation'
  gem 'attribute'
  gem 'casing'
  gem 'clock'
  gem 'configure'
  gem 'collection'
  gem 'cycle'
  gem 'dependency'
  gem 'entity_cache'
  gem 'entity_projection'
  gem 'entity_store'
  gem 'event_source'
  gem 'event_source-postgres'
  gem 'eventide-postgres'
  gem 'identifier-uuid'
  gem 'initializer'
  gem 'log'
  gem 'messaging'
  gem 'messaging-postgres'
  gem 'schema'
  gem 'set_attributes'
  gem 'settings'
  gem 'subst_attr'
  gem 'telemetry'
  gem 'telemetry-logger'
  gem 'transform'
  gem 'validate'
  gem 'virtual'
end
